### ISSUE TITLE
Words containing the string "END" are treated as the symbol END

### ISSUE THREAD

**Issue by trondtynnol** [eddieantonio/vscode-lexc#2]
Words containing the string "END" are treated as the special word END, and thus the rest of the file is shown as a comment.

An example from [giellalt/lang-sme](https://github.com/giellalt/lang-sme):
`fax+N+Sem/Txt+Sg+Nom:fax ENDLEX ; !^LOAN`

**Comment by eddieantonio** [comment]
Okay! The next time you start VSCode it should update to 1.0.4. This should fix the issue:

Before (1.0.3): 
<img width="791" alt="Screen Shot 2021-06-28 at 8 38 11 AM" src="https://user-images.githubusercontent.com/2294397/123655700-73ccfe00-d7ec-11eb-9479-6703e6d70bda.png">

After (1.0.4):
<img width="779" alt="Screen Shot 2021-06-28 at 8 38 46 AM" src="https://user-images.githubusercontent.com/2294397/123655747-821b1a00-d7ec-11eb-9883-be6d1089a9e9.png">

**Comment by trondtynnol** [comment]
Nice,  thank you!

**Comment by trondtynnol** [comment]
Hi! I have come across this problem again when a contlex name ends in '-END', like in line 907 in [this file](https://github.com/giellalt/lang-sme/blob/main/src/fst/stems/numerals.lexc). This probably also applies if the hyphen comes after END.
